const KEY='miao-receipt-data-v2',OLD_KEY='miao-receipt-data-v1';
const icons={餐饮:'🍰',购物:'🛍️',交通:'🚕',娱乐:'🎟️',学习:'📚',其他:'🎀'},colors=['#ffe8ed','#e2f5eb','#fff1c8','#e9e4ff','#dff1ff'];
const starter=[{id:1,type:'expense',name:'草莓奶油蛋糕',price:28,category:'餐饮',date:new Date().toISOString().slice(0,10),note:'甜甜的一天',showPrice:true,collected:true},{id:2,type:'expense',name:'猫爪马克杯',price:49.9,category:'购物',date:'2026-09-05',note:'喝水也要可爱',showPrice:false,collected:true},{id:3,type:'expense',name:'电影票',price:45,category:'娱乐',date:'2026-09-03',note:'喜欢这个结局',showPrice:true,collected:true}];
const cheers=Array.from({length:8},(_,i)=>[`assets/income-cat-${i+1}.webp`,...([['今天也在闪闪发光！','认真赚到的每一笔，都在让小金库变得更有底气。'],['猫猫为你鼓掌！','这是努力开花的声音，记得也奖励一下认真生活的自己。'],['小金库长大一点啦！','慢慢积累也很厉害，你正在靠近想去的地方。'],['收到一份好运气！','今天的你超棒，这份收入值得一个软乎乎的猫猫抱。']][i%4])]);
let items=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem(OLD_KEY)||'null')||starter;items=items.map(x=>({...x,type:x.type||'expense'}));let currentReceipt,filter='all',entryType='expense',imageTarget;
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),money=n=>'¥ '+Number(n).toFixed(2),save=()=>localStorage.setItem(KEY,JSON.stringify(items));$('#itemDate').value=new Date().toISOString().slice(0,10);
function receiptHTML(x){let inc=x.type==='income';return `<div class="paper-receipt"><div class="receipt-head"><b>ฅ 喵 喵 ${inc?'进 账':'杂 货'} 簿 ฅ</b><span>${inc?'MEOW INCOME NOTE':'MEOW MEOW RECEIPT'}</span></div><div class="receipt-line"><span>${x.name}</span><strong>${inc?'+ '+money(x.price):(x.showPrice?money(x.price):'♡ 珍藏品')}</strong></div><div class="receipt-line"><small>${x.category}</small><small>${x.date}</small></div>${x.note?`<div class="receipt-note">“ ${x.note} ”</div>`:''}<div class="receipt-total"><span>${inc?'INCOME':(x.showPrice?'TOTAL':'PRICE')}</span><span>${inc?'+ '+money(x.price):(x.showPrice?money(x.price):'保密喵')}</span></div><div class="receipt-foot">${inc?'GOOD JOB, MEOW! ♡':'THANK MEW! ♡'}</div></div>`}
function render(){let ex=items.filter(x=>x.type!=='income'),ins=items.filter(x=>x.type==='income'),out=ex.reduce((s,x)=>s+ +x.price,0),inc=ins.reduce((s,x)=>s+ +x.price,0);$('#monthTotal').textContent=money(out);$('#monthIncome').textContent=money(inc);$('#monthBalance').textContent=money(inc-out);$('#recentGrid').innerHTML=[...items].reverse().slice(0,3).map(x=>`<article class="expense-card ${x.type==='income'?'income-entry':''}"><div class="expense-icon">${x.type==='income'?'🪙':icons[x.category]||'🎀'}</div><div class="expense-main"><b>${x.name}</b><small>${x.date} · ${x.type==='income'?'收入':x.category}</small></div><strong>${x.type==='income'?'+ ':'- '}${money(x.price)}</strong></article>`).join('')||'<div class="empty-card">还没有记录，写下今天的第一笔吧 ฅ</div>';renderCollection();renderReceipts()}
function renderCollection(){let q=$('#collectionSearch').value.trim(),list=items.filter(x=>x.type!=='income'&&x.collected&&(!q||x.name.includes(q))&&(filter==='all'||(filter==='shown'?x.showPrice:!x.showPrice)));$('#collectionGrid').innerHTML=list.map((x,i)=>`<article class="collection-card"><div class="collection-art" style="--bg:${colors[i%colors.length]}">${x.image?`<img src="${x.image}" alt="${escapeXML(x.name)}的自定义图片">`:icons[x.category]||'🎀'}<button class="image-edit" data-image-id="${x.id}">${x.image?'更换图片':'添加图片'}</button></div><div class="collection-info"><h3>${x.name}</h3><p>${x.note||x.category+' · '+x.date}</p><div class="collection-foot"><span class="price-badge">${x.showPrice?money(x.price):'价格保密'}</span><button class="hide-price" data-toggle-price="${x.id}" title="切换价格显示">${x.showPrice?'◉':'○'}</button></div></div></article>`).join('')||'<div class="empty-card">收藏柜空空的，去记一件喜欢的东西吧。</div>'}
function renderReceipts(){let list=[...items].reverse();$('#receiptWall').innerHTML=list.map(x=>`<article class="receipt-card-wrap" data-receipt="${x.id}">${receiptHTML(x)}</article>`).join('')||'<div class="empty-card">还没有小票，第一张会很特别。</div>'}function openReceipt(x){currentReceipt=x;$('#receiptPreview').innerHTML=receiptHTML(x);$('#receiptDialog').showModal()}
function showCheer(x){let c=cheers[Math.floor(Math.random()*cheers.length)];$('#encouragementCat').src=c[0];$('#encouragementTitle').textContent=c[1];$('#encouragementText').textContent=c[2];$('#encouragementAmount').textContent='+ '+money(x.price);$('#encouragementDialog').showModal()}
function setEntryType(type){entryType=type;$$('.entry-tab').forEach(x=>x.classList.toggle('active',x.dataset.entryType===type));$('.quick-card').classList.toggle('income-mode',type==='income');$('#formHint').textContent=type==='income'?'喵~ 今天有什么进账？':'喵~ 今天买了什么？';$('#nameLabel').textContent=type==='income'?'收入来源':'买了什么';$('#amountLabel').textContent=type==='income'?'收入多少':'花了多少';$('#dateLabel').textContent=type==='income'?'入账日期':'购买日期';$('#itemName').placeholder=type==='income'?'比如：兼职工资':'比如：草莓蛋糕';$('#submitText').textContent=type==='income'?'记下这笔收入':'生成我的小票'}$$('.entry-tab').forEach(b=>b.onclick=()=>setEntryType(b.dataset.entryType));
$('#expenseForm').addEventListener('submit',e=>{e.preventDefault();let inc=entryType==='income',x={id:Date.now(),type:entryType,name:$('#itemName').value.trim(),price:+$('#itemPrice').value,category:inc?'收入':$('#itemCategory').value,date:$('#itemDate').value,note:$('#itemNote').value.trim(),showPrice:inc||$('#showPrice').checked,collected:!inc&&$('#addCollection').checked};items.push(x);save();render();e.target.reset();$('#itemDate').value=new Date().toISOString().slice(0,10);$('#showPrice').checked=$('#addCollection').checked=true;inc?(showCheer(x),toast('进账啦！猫猫来为你庆祝')):(openReceipt(x),toast('记好啦！猫猫帮你收进小票夹了'))});
$$('.nav-btn').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));function showView(v){$$('.view,.nav-btn').forEach(x=>x.classList.remove('active'));$('#'+v).classList.add('active');$(`.nav-btn[data-view="${v}"]`).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}$('#collectionSearch').oninput=renderCollection;$$('.chip').forEach(b=>b.onclick=()=>{$$('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.price;renderCollection()});
document.addEventListener('click',e=>{let p=e.target.closest('[data-toggle-price]');if(p){let x=items.find(x=>x.id==p.dataset.togglePrice);x.showPrice=!x.showPrice;save();render();toast(x.showPrice?'已经标上价格啦':'价格藏起来啦')}let r=e.target.closest('[data-receipt]');if(r)openReceipt(items.find(x=>x.id==r.dataset.receipt));let im=e.target.closest('[data-image-id]');if(im){imageTarget=+im.dataset.imageId;$('#collectionImageInput').click()}});
$('#collectionImageInput').onchange=e=>{let f=e.target.files[0];if(!f)return;let reader=new FileReader();reader.onload=()=>{let im=new Image();im.onload=()=>{let scale=Math.min(1,700/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext('2d').drawImage(im,0,0,c.width,c.height);let x=items.find(x=>x.id===imageTarget);if(x){x.image=c.toDataURL('image/jpeg',.78);save();renderCollection();toast('收藏图片换好啦 ♡')}e.target.value=''};im.src=reader.result};reader.readAsDataURL(f)};
$('#closeDialog').onclick=()=>$('#receiptDialog').close();$('#receiptDialog').onclick=e=>{if(e.target===$('#receiptDialog'))e.target.close()};$('#closeEncouragement').onclick=$('#encouragementOk').onclick=()=>$('#encouragementDialog').close();
$('#copyReceipt').onclick=async()=>{if(!currentReceipt)return;let x=currentReceipt;await navigator.clipboard.writeText(`喵喵小票簿\n${x.name}  ${x.type==='income'?'+ '+money(x.price):(x.showPrice?money(x.price):'价格保密')}\n${x.date} · ${x.category}\n${x.note||''}`);toast('小票内容复制好啦')};$('#saveReceipt').onclick=()=>{if(!currentReceipt)return;let x=currentReceipt,svg=`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="820"><rect width="100%" height="100%" fill="#fffaf0"/><rect x="45" y="45" width="510" height="730" rx="18" fill="#fff"/><text x="300" y="130" text-anchor="middle" font-size="34" fill="#5a3a40">喵 喵 小 票 簿</text><line x1="85" y1="175" x2="515" y2="175" stroke="#dbcac6" stroke-dasharray="12"/><text x="90" y="245" font-size="28" fill="#5a3a40">${escapeXML(x.name)}</text><text x="510" y="245" text-anchor="end" font-size="28" fill="#5a3a40">${x.type==='income'?'+ '+money(x.price):(x.showPrice?money(x.price):'珍藏品')}</text><text x="90" y="310" font-size="22" fill="#9b7b82">${x.date} · ${x.category}</text><rect x="85" y="365" width="430" height="105" rx="14" fill="#fff0f4"/><text x="300" y="430" text-anchor="middle" font-size="22" fill="#75535b">${escapeXML(x.note||'今天也有好好生活')}</text><text x="90" y="595" font-size="25" font-weight="bold" fill="#5a3a40">${x.type==='income'?'INCOME':'TOTAL'}</text><text x="510" y="595" text-anchor="end" font-size="25" fill="#5a3a40">${x.type==='income'?'+ '+money(x.price):(x.showPrice?money(x.price):'保密喵')}</text><text x="300" y="700" text-anchor="middle" font-size="24" fill="#ff7897">THANK MEW! ♡</text></svg>`,a=document.createElement('a');a.href=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));a.download=`喵喵小票-${x.name}.svg`;a.click();toast('小票图片保存好啦')};
function escapeXML(s){return String(s).replace(/[<>&'\"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;',"'":'&apos;','"':'&quot;'}[c]))}function toast(t){let el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}save();render();
